// A list of all actions in the system.
import {createTypes} from 'reduxsauce';

export default createTypes(`
  STARTUP
  INITIALIZED
  APP_STATE
  
  REGISTER
  REGISTER_SUCCESS
  REGISTER_FAILURE
  CLEAR_REGISTRATION_SUCCESS_MESSAGE

  REGISTER_PUSH
  REGISTER_PUSH_SUCCESS
  REGISTER_PUSH_FAILURE
  
  LOGIN
  LOGIN_SUCCESS
  LOGIN_FAILURE

  FB_LOGIN
  FB_LOGIN_SUCCESS
  FB_LOGIN_FAILURE

  GOOGLE_LOGIN
  GOOGLE_LOGIN_SUCCESS
  GOOGLE_LOGIN_FAILURE
  GOOGLE_LOGIN_CANCEL

  GOOGLE_LOGIN_SETUP
  GOOGLE_LOGIN_SETUP_SUCCESS
  GOOGLE_LOGIN_SETUP_FAILURE
  
  GET_TOKEN
  GET_TOKEN_SUCCESS
  GET_TOKEN_FAILURE

  LOGOUT
  
  GET_ME
  GET_ME_SUCCESS
  GET_ME_FAILURE
  
  GET_PROFILE
  GET_PROFILE_SUCCESS
  GET_PROFILE_FAILURE
  
  RESET_PASSWORD
  RESET_PASSWORD_SUCCESS
  RESET_PASSWORD_FAILURE

  ONE_SIGNAL_IDS_AVAILABLE
  SUBSCRIBE_TO_ONE_SIGNAL
  
  UPDATE_PROFILE
  UPDATE_PROFILE_SUCCESS
  UPDATE_PROFILE_FAILURE

  ADD_FEEDBACK
  ADD_FEEDBACK_SUCCESS
  ADD_FEEDBACK_FAILURE

  ADD_ARTICLE
  ADD_ARTICLE_SUCCESS
  ADD_ARTICLE_FAILURE
`);
